"""add missing columns to steps table

Revision ID: 51c030a32835
Revises: 21535e685c4c
Create Date: 2026-04-08 15:02:50.085359

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '51c030a32835'
down_revision: Union[str, Sequence[str], None] = '21535e685c4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('steps', sa.Column('content', sa.String(length=1000), nullable=True))
    op.add_column('steps', sa.Column('fileId', sa.String(length=255), nullable=True))
    op.add_column('steps', sa.Column('order', sa.Integer(), nullable=True))
    op.execute("UPDATE steps SET \"order\" = 0 WHERE \"order\" IS NULL")
    op.alter_column('steps', 'order', nullable=False)
    op.alter_column('steps', 'isCompleted',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('steps', 'isCompleted',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_column('steps', 'order')
    op.drop_column('steps', 'fileId')
    op.drop_column('steps', 'content')
    # ### end Alembic commands ###
