"""set file id as UUID

Revision ID: e602d7c5f25d
Revises: b3654d556b11
Create Date: 2026-05-26 11:29:07.001729

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e602d7c5f25d'
down_revision: Union[str, Sequence[str], None] = 'b3654d556b11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('steps', sa.Column('fileIds', sa.ARRAY(sa.UUID()), nullable=True))
    op.drop_column('steps', 'fileId')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('steps', sa.Column('fileId', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_column('steps', 'fileIds')
    # ### end Alembic commands ###
